---
- hosts: projDevops
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        update_cache: yes
        cache_valid_time: 3600 
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - python-apt
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria o banco no MySQL'
      become: yes
      mysql_db:
        name: mysqldb
        login_user: root
        state: present

    - name: 'Cria usuario no MySQL'
      become: yes
      mysql_user:
        login_user: root
        name: 'tiago'
        password: 12345
        priv: '*.*:ALL'
        state: present
        host: '{{ item }}'
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '177.17.177.1'
        - '177.17.177.40'
        
    - name: 'Configura MySQL para aceitar conexões remotas'
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
       - restart mysql

    - name: Instalando git
      become: yes
      shell: apt-get install -y git

    - name: Baixando primeiro Microserviço
      become: yes
      git:
        repo: https://github.com/tdsmarques/microservico_cliente.git
        dest: /srv/cliente

    - name: baixando segundo Microserviço
      become: yes
      git:
        repo: https://github.com/tdsmarques/microservico_filme.git
        dest: /srv/filme

    - name: Install packages based on package.json.
      npm:
        path: /srv/filme

    - name: Install packages based on package.json.
      npm:
        path: /srv/cliente


    - name: Iniciando Serviço de Filme
      become: yes
      shell:
        "npm run test"
      args:
        chdir: "/srv/filme"
      register: Rodando Testes Servico 1/2

    - name: Iniciando Serviço de Cliente
      shell:
        "npm runt test"
      args:
        chdir: "/srv/cliente"
      register: Rodando Testes Servico 2/2